// <auto-generated />
namespace Ornek1_TablolarArasiIliskiler.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class bes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bes));
        
        string IMigrationMetadata.Id
        {
            get { return "202205290932011_bes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
